version: '1.0'

services:
  db:
    image: mysql:8.0.34
    restart: always
    environment:
      MYSQL_DATABASE: 'spring-rest-api'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

# Names our volume
volumes:
  my-db:
